operator: operators.ExternalTable
source_objects:
  - 'schedule/processed/*/routes.txt'
destination_project_dataset_table: "gtfs_schedule_external.routes"
skip_leading_rows: 1
schema_fields:
  - name: calitp_itp_id
    type: INTEGER
  - name: calitp_url_number
    type: INTEGER
  - name: route_id
    type: STRING
  - name: route_type
    type: STRING

    # conditional
  - name: agency_id
    type: STRING
  - name: route_short_name
    type: STRING
  - name: route_long_name
    type: STRING
  - name: route_desc
    type: STRING

    # optional
  - name: route_url
    type: STRING
  - name: route_color
    type: STRING
  - name: route_text_color
    type: STRING
  - name: route_sort_order
    type: STRING
  - name: continuous_pickup
    type: STRING
  - name: continuous_drop_off
    type: STRING

  - name: calitp_extracted_at
    type: DATE
